export default {
  REQUEST_REPOS: 'REQUEST_REPOS',
  RECEIVE_REPOS: 'RECEIVE_REPOS',
  SET_REPOS: 'SET_REPOS',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_TIME: 'SET_TIME',
  SET_EMAIL: 'SET_EMAIL',
  SET_USER: 'SET_USER'
}
